### ISSUE TITLE
about tello Extension plug-in problem

### ISSUE THREAD

**Issue by eclipsequote** [kebhr/scratch3-tello#1]
すみません、あなたが開発したtelloプラグインを見て、とても好きです。

しかし、使っているうちに、telloの状態値が正常に戻らないことが分かりました。このプラグインにビデオ伝送機能を追加できますか？

**Comment by kebhr** [comment]
使ってくれてありがとうございます。

> telloの状態値が正常に戻らないことが分かりました。
この問題について詳しく教えていただいてもいいですか？
Telloとの通信は改善することができると考えています。その参考になればと思います。

> このプラグインにビデオ伝送機能を追加できますか？
ビデオ伝送機能を追加するために、現在いくつかの試験を行っています。
現在のところ、ffmpeg などの外部ライブラリを読み込まずに、ビデオを取り入れることができていません。
互換性を高めるために、外部ライブラリの使用をなるべく控えたいと思っています。
もしあなたがPull-Requestを作成すれば、私はそれをレビューすることができます。お待ちしています！

(I'm glad you are writing in Japanese. but I append an English reply because it is helpful for someone else.)

> telloの状態値が正常に戻らないことが分かりました。
I'd like to know more details about this problem.
I think that communication with Tello can be improved. I think your reply will be helpful.

> このプラグインにビデオ伝送機能を追加できますか？
Several tests are currently underway to add video transmission. At the moment, I didn't succeed to import video without using an external library such as ffmpeg. For compatibility, I'd like to avoid using an external library as much as possible.

If you create a Pull-Request, I'm glad to review it. I'm looking forward to your contribution!

**Comment by eclipsequote** [comment]
あなたの返事を見てとても嬉しいです。

>この問題について詳しく教えていただいてもいいですか？
 >Telloとの通信は改善することができると考えています。その参考になればと思います。
 
 PCは無人機にコマンドを送ることができますが、無人機の状態値は‘null’であり、PCと無人機は長時間の接続を維持することができず、毎回の接続は数分間しか維持できません。私が使っているPCシステムはUbuntu 18.04.1で、scratchバージョンは3.8.0です。Ubuntuシステムが「Scrtch Link」をインストールできません。故障はこれと関係がありますか？
 
The PC can send commands to the Tello, but the status value of the Tello is "null", and the PC and the Tello can not maintain a long-term connection, each connection can only be maintained for a few minutes. My PC system is Ubuntu 18.04.1, and scratch version is 3.8.0. Ubuntu cannot install 'Scratch Link'. Is the failure related to this?

**Comment by kebhr** [comment]
詳細な情報を教えてくれてありがとうございます。

報告していただいた問題について、私も調べてみます。
- Telloとの通信は一般的なUDPで行われていること
- Scratch Link や Scratch Link で使用されている Bluetooth を使用していないこと

から、Ubuntuでなくても問題が起こると考えています。（私はmacOSを使用しています。）

私はこの問題に調査し、結果を書き込みます。
ありがとうございます。

---

Thank you for telling me the details.

I'll look into the problem you reported.
I think this problem will occur even if you are not using Ubuntu for the following reasons.
- Communication with Tello is through UDP
- Not using Scratch Link or Bluetooth (used by Scratch Link)

I'll investigate this problem and write the result.
Thanks again.

**Comment by kebhr** [comment]
詳細な情報を教えてくれてありがとうございます。

報告していただいた問題について、私も調べてみます。
- Telloとの通信は一般的なUDPで行われていること
- Scratch Link や Scratch Link で使用されている Bluetooth を使用していないこと

から、Ubuntuでなくても問題が起こると考えています。

ちなみに、Telloの状態値はどのように取得しましたか？
私はこの拡張機能を開発しているときにはWiresharkを開き、UDPパケットを読んでいます。
同じ方法でしょうか？

私はこの問題に調査し、結果を書き込みます。
ありがとうございます。

---

Thank you for telling me the details.

I'll look into the problem you reported.

I think this problem will occur even if you are not using Ubuntu for the following reasons.
- Communication with Tello is through UDP
- Not using Scratch Link or Bluetooth (used by Scratch Link)

Please tell me another one: How did you check Tello’s status value?
When I’m developing this extension, I capture UDP packets via Wireshark.
Is your method the same way?

I'll investigate this problem and write the result.
Thanks again.

**Comment by eclipsequote** [comment]
すみません、私もWireharkでUDPパケットを捕獲しました。ポート番号は8890です。Telloの姿勢データが得られますが、scratchで戻ってくるのは全部null値です。

Hello, I also capture UDP packets through Wireshark. The port number is 8890. I can get the attitude data of Tello, but the returned values in scratch are all null.

**Comment by kebhr** [comment]
こんにちは。
報告していただいたように、Telloの姿勢データの取得について、問題が起こっていることが確認できました。
私はこの問題について修正に取り組みます。

---

Hi.
As you said, I confirmed the problem of processing Tello's attitude data.
I'm trying to fix this problem.

**Comment by eclipsequote** [comment]
ありがとうございます。

Thank you.

**Comment by kebhr** [comment]
こんにちは。

私は先ほど、この問題を解決するコードをコミットしました。
もし良かったら、試してみてください！

I made a change to resolve this problem. https://github.com/kebhr/scratch3-tello/commit/3d3ff5b3a3acadfe6670a417b749a4e541fe6adb
Please build it if you don't mind!

**Comment by eclipsequote** [comment]
すみません、あなたが提出したコードをテストしましたが、scratchはまだ返却されていません。これはソフトウェアバージョンの問題かもしれません。あなたが使っているnodeとelectronのバージョン番号はいくらですか？私のバージョン番号は：
>node 12.16.1
>electron 6.1.7

Hi, I have tested the code you submitted, but scratch still returns null value. I guess this may be a software version problem. I want to know what the node and electron version numbers you use? My version number is:
>node 12.16.1
>electron 6.1.7

**Comment by kebhr** [comment]
私が環境を構築したとき、scratch-desktop は Electron 4.2.9 を使用していたため、私は今も Electron 4.2.9 を使用しています。
しかしながら、最新の scratch-desktop は Electron 6.1.7 を使用しています。https://github.com/LLK/scratch-desktop/blob/develop/package.json
私の環境を最新の scratch-desktop に合うよう更新し、再び調査します。

Ah!
My environment was built when scratch-desktop uses Electron 4.2.9, so I’m using Electron 4.2.9 .
But currently scratch-desktop uses Electron 6.1.7 . https://github.com/LLK/scratch-desktop/blob/develop/package.json
I’ll update my environment to adapt latest scratch-desktop then test again.

**Comment by eclipsequote** [comment]
すみません、tello Extensionを使う過程で以下の二つの問題を発見しました。

1. しばらく運転すると、scratchはtelloとの接続を失い、コマンドを送信できなくなります。
2. 退出するとき、scratchが閉じられない場合があります。


Hi, in the process of using the Tello extension, I found the following two problems:

1. After running for a period of time, scratch will lose its connection with Tello and cannot send commands;
2. When you want to exit, scratch will fail to close the exit.

**Comment by kebhr** [comment]
1つ目の問題については、定期的にTelloに対し何らかのコマンドを送り続けることで、コネクションを維持し続けられそうに見えます。
こちらでも長時間の稼働を実験してみます。

2つ目の問題が気になります。
Scratchが閉じられない時、エラーは表示されますか？
この問題は何回に1回ほど起こりますか？

First problem: I think it can keep the connection going by periodically sending some command to Tello.
I will test with running longer.

I'm curious about the second problem.
I have two questions:
- When scratch fails to close the exit, any error is displayed?
- How often happen to this problem? (e.g. once in three times)

**Comment by eclipsequote** [comment]
> Scratchが閉じられない時、エラーは表示されますか？

scratchが終了できない時、chrome開発ツールはエラー情報を報告していません。

しかし、次のような警告があります：

1.Warning: Failed prop type: The prop `canModifyCloudData` is marked as required in `CloudManager`, but its value is `undefined`.
    in CloudManager

2.Warning: Failed prop type: Invalid prop `children` supplied to `ContextMenuTrigger`, expected a ReactNode.
    in ContextMenuTrigger

> この問題は何回に1回ほど起こりますか？

1.scratchが突然telloにコマンドを送信できなくなった場合（但し、scratchは依然としてtello状態値を受信することができる）。

2.コンピュータとtelloがwifi接続を確立する前にscratchを開いて、telloプラグインを使う場合。

以上の二つの場合はscratchが終了できない場合があります。
 

> When scratch fails to close the exit, any error is displayed?

When scratch cannot exit, the chrome development tool does not report an error.

However, you will receive the following warning message:

1.Warning: Failed prop type: The prop `canModifyCloudData` is marked as required in `CloudManager`, but its value is `undefined`.
    in CloudManager

2.Warning: Failed prop type: Invalid prop `children` supplied to `ContextMenuTrigger`, expected a ReactNode.
    in ContextMenuTrigger

> How often happen to this problem? (e.g. once in three times)

1. When scratch suddenly fails to send a command to Tello (but scratch can still receive the Tello status value at this time);

2. When you open scratch and use Tello plug-in before the computer establishes WiFi connection with Tello;

In both cases, scratch cannot exit.

**Comment by kebhr** [comment]
詳細を教えていただきありがとうございます。
これから数日の間、私は作業に取りかかることができませんが、可能な限り早く調査に着手します。

Thanks for sharing the details with us.
I can't get started over the next few days, but I'll get started as soon as I can.

**Comment by eclipsequote** [comment]
はい、ありがとうございます。

Well, thank you very much.

**Comment by kebhr** [comment]
macOS環境で調査しましたが、不具合を確認することができませんでした。
Electronのウィンドウ管理はmacOSの場合のみ特別になっているため、現在Ubuntu 18.04の環境を用意しています。

I investigated on a macOS, but was unable to confirm the problem.
Electron's window management is special on macOS, so I'm just preparing Ubuntu 18.04 .

**Comment by kebhr** [comment]
Ubuntu 18.04.1 を実機(ThinkPad X250)に導入し、この問題について検証を行いましたが、確認することができませんでした。
お手数ですが、もう一度ビルドから行っていただけないでしょうか？

注: https://github.com/kebhr/scratch3-tello/issues/1#issuecomment-602413243 にてご報告頂いた警告はこちらでも確認できました。ただし、Scratchが終了しない問題は確認できませんでした。

### テスト手順
以下の手順によりテストを行いました。
```bash
$ mkdir scratch3-tello
$ cd scratch3-tello
$ wget https://raw.githubusercontent.com/kebhr/scratch3-tello/master/build.sh
$ chmod +x build.sh
$ vi build.sh ("cp -r scratch3-tello/ ./" を "cp -r scratch3-tello/* ./" に変更しました)
$ ./build.sh
$ npm scratch-desktop
$ npm run build-gui
$ npm start
```
1. Tello に接続
2. Scratch で Tello の拡張機能を選択
3. いくつかのパラメータを表示させる
4. いくつかのコマンドを送信する

時々コマンドを送信しながら、10分ほどテストしましたが、正常に動作しました。

### 環境
以下の環境でテストしました。
- ThinkPad X250
- Ubuntu 18.04.1
- Node 12.16.1
- Electron 6.1.7

---

I installed Ubuntu 18.04.1 on a real machine (ThinkPad X250), and test these issues you reported.
However, I've not been able to confirm the issues.
Sorry, can I ask you to try it again from the build?

Note: Some warning you reported in https://github.com/kebhr/scratch3-tello/issues/1#issuecomment-602413243 is happened, but failing to close is not happened.

### Test procedure
I tested with following steps.
```bash
$ mkdir scratch3-tello
$ cd scratch3-tello
$ wget https://raw.githubusercontent.com/kebhr/scratch3-tello/master/build.sh
$ chmod +x build.sh
$ vi build.sh (I changed cp -r scratch3-tello/ ./ to cp -r scratch3-tello/* ./ )
$ ./build.sh
$ npm scratch-desktop
$ npm run build-gui
$ npm start
```
1. connect Tello's wifi
2. choose Tello Extension in Scratch.
3. show some status
4. send some commands.

I repeated the command transmission intermittently for about 10 minutes, but it is worked normally.

### Environment
My environment is:
- ThinkPad X250
- Ubuntu 18.04.1
- Node 12.16.1
- Electron 6.1.7

**Comment by eclipsequote** [comment]
OK、私はあなたの方法に従って開発環境をリファクタリングしてから、もう一度テストします。

OK, I will refactor the development environment according to your method, and then test again.

**Comment by eclipsequote** [comment]
こんにちは、終了できないという問題を解決するために、コードを再コンパイルしてパッケージ化しました。
制御コマンドキャッシュ機能をオフにして、TELLOにコマンドを送れない問題を解決しました。
ご協力ありがとうございます。

Hello, I recompiled and packaged the code to solve the problem of not being able to exit.
I turned off the control command cache function and solved the problem that I couldn't send commands to TELLO.
thank you very much for your help.
