### ISSUE TITLE
wrong behaviour

### ISSUE THREAD

**Issue by ismaildakrory** [kebhr/scratch3-tello#10]
when I execute takeoff Tello takes off and starts drifting to the back right.
and it won't receive any other command.
then after some seconds it start blinking red and loose connection to scratch

**Comment by kebhr** [comment]
If the LED on the Tello is blinking red, it indicates low battery.
Please use scratch-tello with a fully charged battery.

If you are unable to use scratch-tello, but can use the smartphone version of the official Tello app successfully, please reopen this issue.

**Comment by ismaildakrory** [comment]
Thank you so much for your response,

I can successfully use the Tello app and DroneBlocks app, Scratch-tello connects successfully and it can get the drone to take off,
But after taking off the drone drifts to back right slowly and constantly, then land and flash red (as signal lost).
then I have to close and reopen the Scratch-tello to get it green and connected again.
the battery is fully charged all the time.

I don't know if I'm missing something or it's problem with my windows/drone or even the connection, but with DroneBlocks, I can do loops of commands and everything works well.

Thank you for your time
