### ISSUE TITLE
Use with mission pads from DJI Tello EDU

### ISSUE THREAD

**Issue by andrew-m-j** [kebhr/scratch3-tello#13]
I am just getting started with the DJI Tello. I have the EDU version that also includes some mission pads that can be detected by the sensor on the drone and uniquely identified by an integer number. There are some other commands available, described here: https://dl-cdn.ryzerobotics.com/downloads/Tello/Tello%20Mission%20Pad%20User%20Guide.pdf.

Would you consider adding these commands to the scratch extension?

**Comment by kebhr** [comment]
I will add these features in the next release. Thanks for telling me information.
