### ISSUE TITLE
how to connect tello drone to our exe

### ISSUE THREAD

**Issue by PatelManav20** [kebhr/scratch3-tello#16]
I have added tello extension to my exe and all the blocks are loaded successfully but i cannot able to connect it to tello drone.

**Comment by kebhr** [comment]
Hello.

At first, before starting Scratch3-Tello, connect to the Tello's Wi-Fi.
If you start Scratch3-Tello after connecting to the Tello's Wi-Fi, you will be connected to the Tello from the beginning.

If you have followed the steps above and still cannot connect, please share the following information with me.

=================
- What operating system are you using?
- What color does the LED on the Tello glow when it cannot connect? Is it lit or flashing?
- (if you have an iOS or Android device) Can you connect to the Tello using the Tello app?

=================

**Comment by kebhr** [comment]
close this issue due to inactive. please reopen if you need.
