### ISSUE TITLE
functional?

### ISSUE THREAD

**Issue by geniuscoderslive** [kebhr/scratch3-tello#4]
Hey @kebhr 

I am so excited to see this repo. I would love to get students up and running with Tello and Scratch 3. Is the current build functional (sorry, I didn't see any details in the readme/etc.)?

Thanks much.
Andy

**Comment by kebhr** [comment]
Hi @geniuscoderslive

Thank you for finding out this repository.
Currently, I don't provide pre-built binary, but I have confirmed that current build works properly.
I'm now preparing to distribute the pre-built binary.

If you need the binary immediately, you can build it by following the steps below. (Node.js and git required)
https://github.com/kebhr/scratch3-tello#build

Note: If you have a successful build and are unable to connect Scratch3 to Tello, please connect to Tello's Wi-Fi and start Scratch3.

Thanks.

**Comment by geniuscoderslive** [comment]
Hey thanks much for the response and for working on this amazing project!
No, I will not build it and will wait for your official  binary/release.
Any thoughts on timeframe please?

**Comment by kebhr** [comment]
I think I'll be able to release it for Windows and Linux in a few days.
Build for macOS is expected to be delayed due to certificate issues.

**Comment by geniuscoderslive** [comment]
We use windows/Chromebooks almost exclusively. That would be super duper
fanatic!!! TIA!

**Comment by kebhr** [comment]
I'm continuing to work on it, but it's only failing for Windows due to an unknown problem...

**Comment by geniuscoderslive** [comment]
Really appreciate it. Good luck! Please keep me posted.

**Comment by kebhr** [comment]
Thanks for waiting.
I've released first version.
Please check it out from here: https://github.com/kebhr/scratch3-tello/releases/tag/v1.0.0 .

**Comment by geniuscoderslive** [comment]
That's great. You should post about it on Scratch forums! Unfortunately I
just sent my Tello for repair so I can't test your release just yet and
will have to wait :(

Keep up the great work though! I look forward to playing with it soon!

Andy

**Comment by kebhr** [comment]
It's been inactive for a long time, so I'm closing it. If you have any further questions, please create new issue!
