### ISSUE TITLE
Mac version crashes on startup

### ISSUE THREAD

**Issue by ackerthehacker2** [kebhr/scratch3-tello#8]
Using the compiled mac versuin hwere ....

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Scratch Desktop [8839]
Path:                  /Applications/Scratch Desktop.app/Contents/MacOS/Scratch Desktop
Identifier:            edu.mit.scratch.scratch-desktop
Version:               3.10.4 (3.10.4)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               506

Date/Time:             2021-11-12 21:07:46.8852 -0600
OS Version:            macOS 12.1 (21C5031d)
Report Version:        12
Bridge OS Version:     6.1 (19P50631c)
Anonymous UUID:        9B4A7380-34AD-19A1-468F-A6CCBA25ABC6

Time Awake Since Boot: 1700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: /Applications/Scratch Desktop.app/Contents/MacOS/Scratch Desktop
Reason: tried: '/Applications/Scratch Desktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Applications/Scratch Desktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file)
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: /Applications/Scratch Desktop.app/Contents/MacOS/Scratch Desktop
Reason: tried: '/Applications/Scratch Desktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Applications/Scratch Desktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file)

Thread 0 Crashed:
0   dyld                          	       0x10e3b60ce __abort_with_payload + 10
1   dyld                          	       0x10e3cc1cf abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x10e3cc201 abort_with_payload + 9
3   dyld                          	       0x10e37a613 dyld4::halt(char const*) + 375
4   dyld                          	       0x10e37655d dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3955
5   dyld                          	       0x10e3754b4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bc367678  rdx: 0x00007ff7bc367ae0
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bc3676c0  rsp: 0x00007ff7bc367678
   r8: 0x00007ff7bc3676e0   r9: 0x0000000000000000  r10: 0x000000000000008c  r11: 0x0000000000000246
  r12: 0x000000000000008c  r13: 0x00007ff7bc367ae0  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x000000010e3b60ce  rfl: 0x0000000000000246  cr2: 0x000000010e37ce3c
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x10e370000 -        0x10e3dbfff dyld (*) <15411f2c-1dc7-3958-b73d-d85cdf549ec1> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=800K resident=0K(0%) swapped_out_or_unallocated=800K(100%)
Writable regions: Total=9224K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9224K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                              32K        3 
__DATA_CONST                        80K        1 
__LINKEDIT                         216K        3 
__TEXT                             596K        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                             65.9M       15 

-----------
Full Report
-----------

{"app_name":"Scratch Desktop","timestamp":"2021-11-12 21:07:46.00 -0600","app_version":"3.10.4","slice_uuid":"596191eb-2c06-339c-917c-d986342c029e","build_version":"3.10.4","platform":1,"bundleID":"edu.mit.scratch.scratch-desktop","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.1 (21C5031d)","incident_id":"513CAC25-DDBA-4CCE-AE52-4D0FF2467759","name":"Scratch Desktop"}
{
  "uptime" : 1700,
  "procLaunch" : "2021-11-12 21:07:44.9062 -0600",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 506,
  "deployVersion" : 210,
  "modelCode" : "iMacPro1,1",
  "procStartAbsTime" : 1698719613452,
  "coalitionID" : 2089,
  "osVersion" : {
    "train" : "macOS 12.1",
    "build" : "21C5031d",
    "releaseType" : "User"
  },
  "captureTime" : "2021-11-12 21:07:46.8852 -0600",
  "incident" : "513CAC25-DDBA-4CCE-AE52-4D0FF2467759",
  "bug_type" : "309",
  "pid" : 8839,
  "procExitAbsTime" : 1700697116499,
  "cpuType" : "X86-64",
  "procName" : "Scratch Desktop",
  "procPath" : "\/Applications\/Scratch Desktop.app\/Contents\/MacOS\/Scratch Desktop",
  "bundleInfo" : {"CFBundleShortVersionString":"3.10.4","CFBundleVersion":"3.10.4","CFBundleIdentifier":"edu.mit.scratch.scratch-desktop"},
  "storeInfo" : {"deviceIdentifierForVendor":"665605F8-4558-5D41-A526-23F69C453296","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "edu.mit.scratch.scratch-desktop",
  "crashReporterKey" : "9B4A7380-34AD-19A1-468F-A6CCBA25ABC6",
  "bridgeVersion" : {"build":"19P50631c","train":"6.1"},
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/Electron Framework.framework\/Electron Framework","Referenced from: \/Applications\/Scratch Desktop.app\/Contents\/MacOS\/Scratch Desktop","Reason: tried: '\/Applications\/Scratch Desktop.app\/Contents\/MacOS\/..\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file), '\/Applications\/Scratch Desktop.app\/Contents\/MacOS\/..\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file), '\/Library\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file), '\/System\/Library\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file)"]},
  "asi" : {"dyld":["Library not loaded: @rpath\/Electron Framework.framework\/Electron Framework","Referenced from: \/Applications\/Scratch Desktop.app\/Contents\/MacOS\/Scratch Desktop","Reason: tried: '\/Applications\/Scratch Desktop.app\/Contents\/MacOS\/..\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file), '\/Applications\/Scratch Desktop.app\/Contents\/MacOS\/..\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file), '\/Library\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file), '\/System\/Library\/Frameworks\/Electron Framework.framework\/Electron Framework' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":91233,"threadState":{"r13":{"value":140701991336672},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701991335648},"cr2":{"value":4533505596},"rdx":{"value":140701991336672},"r10":{"value":140},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4533739726,"matchesCrashFrame":1},"rbp":{"value":140701991335616},"rsp":{"value":140701991335544},"r12":{"value":140},"rcx":{"value":140701991335544},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":286926,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":377295,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":377345,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42515,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":25949,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3955,"imageIndex":0},{"imageOffset":21684,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4533452800,
    "size" : 442368,
    "uuid" : "15411f2c-1dc7-3958-b73d-d85cdf549ec1",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703231553536,
  "size" : 15218327552,
  "uuid" : "4615d93b-88ac-3433-9374-0d7be43ddd95"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=800K resident=0K(0%) swapped_out_or_unallocated=800K(100%)\nWritable regions: Total=9224K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9224K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                              32K        3 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         216K        3 \n__TEXT                             596K        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                             65.9M       15 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "60ef663fa2f864203caf575c"
      },
      "deploymentId" : 250000055
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 250000007
    },
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 250000013
    },
    {
      "rolloutId" : "5ffde50ce2aacd000d47a95f",
      "factorPackIds" : {

      },
      "deploymentId" : 250000063
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 250000154
    },
    {
      "rolloutId" : "602ad4dac86151000cf27e46",
      "factorPackIds" : {

      },
      "deploymentId" : 250000250
    },
    {
      "rolloutId" : "601d9415f79519000ccd4b69",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "6184371b8763315b96047a4d"
      },
      "deploymentId" : 250000308
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by kebhr** [comment]
Hello, @ackerthehacker2 .
Thanks for the report.
I've confirmed this issue.
I just re-uploaded the binary for macOS. Please feel free to try this binary.
https://github.com/kebhr/scratch3-tello/releases/tag/v1.1.0

Please let me know if the issue recurs.
Thanks.

**Comment by ackerthehacker2** [comment]
That fixed the problem …thanx ….
