### ISSUE TITLE
¿Bloque "flip" en extensión tello para Scratch 3.0?

### ISSUE THREAD

**Issue by DADIF45** [kebhr/scratch3-tello#9]
Buenas tardes, 
Me gustaría saber cómo codificar un vuelo de dron tipo "Flip" con los bloques que se cargan a través de la extensión tello añadida a Scratch Desktop. Gracias!

**Comment by kebhr** [comment]
Hola, @DADIF45 .
Actualmente, no es posible "flip" Tello con Scratch3-tello, pero es técnicamente posible y se añadirá pronto.
Gracias por la solicitud de la función!

**Comment by kebhr** [comment]
@DADIF45 
Siento haber tardado tanto en añadir el comando.
He añadido el comando de volteo en la v1.3.0, que se ha publicado hoy.
https://github.com/kebhr/scratch3-tello/releases/tag/v1.3.0
